name: Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: team_8h6mDTKHrbmd2AZ63kpBoiFR
          VERCEL_PROJECT_ID: prj_FpGqVa9NFGp61AytxbquqOvv02or
        run: vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}" && vercel build --prod --token "${{ secrets.VERCEL_TOKEN }}" && vercel deploy --prebuilt --prod --token "${{ secrets.VERCEL_TOKEN }}"
